# -*- coding: utf-8 -*-
"""ndvi_map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Farahmand1212/10423c430bcb2b884003c4f3f7b8ea35/ndvi_map.ipynb
"""

!pip install geemap rioxarray matplotlib xarray

import ee
import geemap
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr
import rioxarray
import pandas as pd

# Initialize EE
ee.Authenticate()
ee.Initialize(project='ee-farahamandasadullah')

Map = geemap.Map()
Map

aoi = Map.user_roi

print(da.coords)

s2 = (ee.ImageCollection("COPERNICUS/S2_SR")
      .filterBounds(aoi)
      .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE',20)))

def add_ndvi(img):
    return img.addBands(img.normalizedDifference(['B8','B4']).rename('NDVI'))

s2 = s2.map(add_ndvi)

years = list(range(2018, 2027))
ndvi_rasters = []

for year in years:
    start = ee.Date.fromYMD(year,1,1)
    end   = ee.Date.fromYMD(year,12,31)
    yearly = s2.filterDate(start,end)
    mean_ndvi = yearly.select('NDVI').mean().clip(aoi)

    # Export to local temp GeoTIFF
    filename = f'NDVI_{year}.tif'
    geemap.ee_export_image(mean_ndvi,
                           filename=filename,
                           scale=10,
                           region=aoi)

    ndvi_rasters.append(filename)

ndvi_arrays = []

for f in ndvi_rasters:
    ds = rioxarray.open_rasterio(f, masked=True)
    ndvi_arrays.append(ds)

# Stack into xarray DataArray with 'year' dimension
da = xr.concat(ndvi_arrays, dim=pd.Index(years, name='year'))

import matplotlib.pyplot as plt

# Create 3x3 subplot figure
fig, ax = plt.subplots(3, 3, figsize=(12, 10), constrained_layout=True)

# Flatten axes for easy indexing
ax = ax.flatten()

# Plot each NDVI map separately
da.sel(year=years[0]).plot(
    x='x',
    y='y',
    ax=ax[0],
    cmap='RdYlGn',
    robust=True,
    add_colorbar=True
)

da.sel(year=years[1]).plot(
    x='x',
    y='y',
    ax=ax[1],
    cmap='RdYlGn',
    robust=True,
    add_colorbar=True
)

da.sel(year=years[2]).plot(
    x='x',
    y='y',
    ax=ax[2],
    cmap='RdYlGn',
    robust=True,
    add_colorbar=True
)

da.sel(year=years[3]).plot(
    x='x',
    y='y',
    ax=ax[3],
    cmap='RdYlGn',
    robust=True,
    add_colorbar=True
)

da.sel(year=years[4]).plot(
    x='x',
    y='y',
    ax=ax[4],
    cmap='RdYlGn',
    robust=True,
    add_colorbar=True
)

da.sel(year=years[5]).plot(
    x='x',
    y='y',
    ax=ax[5],
    cmap='RdYlGn',
    robust=True,
    add_colorbar=True
)

da.sel(year=years[6]).plot(
    x='x',
    y='y',
    ax=ax[6],
    cmap='RdYlGn',
    robust=True,
    add_colorbar=True
)

da.sel(year=years[7]).plot(
    x='x',
    y='y',
    ax=ax[7],
    cmap='RdYlGn',
    robust=True,
    add_colorbar=True
)

da.sel(year=years[8]).plot(
    x='x',
    y='y',
    ax=ax[8],
    cmap='RdYlGn',
    robust=True,
    add_colorbar=True
)

# Titles
for i, year in enumerate(years):
    ax[i].set_title(f'NDVI {year}')

plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Compute mean NDVI per year
mean_ndvi = [da.sel(year=year).mean().values for year in years]

# Compute standard deviation per year
std_ndvi = [da.sel(year=year).std().values for year in years]

# Plot line chart
plt.figure(figsize=(8,4))
plt.plot(years, mean_ndvi, marker='o', color='green', linewidth=2)

# Add STD error bars
plt.errorbar(years, mean_ndvi, yerr=std_ndvi, fmt='none', ecolor='gray', capsize=4)

plt.title('Mean NDVI per Year', fontsize=13, fontweight='bold')
plt.xlabel('Year', fontsize=14)
plt.ylabel('Mean NDVI', fontsize=14)
plt.ylim(-0.1, 1)  # NDVI typically ranges -1 to 1
plt.grid(True, linestyle='--', alpha=0.6)

# Highlight points with color based on NDVI value
for x, y in zip(years, mean_ndvi):
    if y < 0:  # water or non-vegetated
        color = 'blue'
    elif y < 0.2:  # bare soil
        color = 'brown'
    elif y < 0.5:  # low vegetation
        color = 'orange'
    else:  # dense vegetation
        color = 'green'
    plt.scatter(x, y, color=color, s=100, edgecolor='k', zorder=5)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Compute mean NDVI per year
mean_ndvi = [da.sel(year=year).mean().values for year in years]

# Compute standard deviation per year
std_ndvi = [da.sel(year=year).std().values for year in years]

# Plot line chart
plt.figure(figsize=(8,4))
plt.plot(years, mean_ndvi, marker='o', color='green', linewidth=2)

# Add shaded STD band
plt.fill_between(years,
                 np.array(mean_ndvi) - np.array(std_ndvi),
                 np.array(mean_ndvi) + np.array(std_ndvi),
                 color='green', alpha=0.2)

plt.title('Mean NDVI per Year', fontsize=13, fontweight='bold')
plt.xlabel('Year', fontsize=14)
plt.ylabel('Mean NDVI', fontsize=14)
plt.ylim(-0.1, 1)  # NDVI typically ranges -1 to 1
plt.grid(True, linestyle='--', alpha=0.6)

# Highlight points with color based on NDVI value
for x, y in zip(years, mean_ndvi):
    if y < 0:  # water or non-vegetated
        color = 'blue'
    elif y < 0.2:  # bare soil
        color = 'brown'
    elif y < 0.5:  # low vegetation
        color = 'orange'
    else:  # dense vegetation
        color = 'green'
    plt.scatter(x, y, color=color, s=100, edgecolor='k', zorder=5)

plt.show()

import matplotlib.pyplot as plt
from matplotlib.ticker import FormatStrFormatter
import matplotlib.colors as mcolors

fig, axes = plt.subplots(3, 3, figsize=(12,10), constrained_layout=True)
axes = axes.flatten()

vmin, vmax = -1, 1  # NDVI range

# Use x and y as lon/lat
lon = da.x.values
lat = da.y.values

# NDVI colormap: brown → yellow → green
ndvi_cmap = plt.get_cmap('RdYlGn')
norm = mcolors.Normalize(vmin=vmin, vmax=vmax)

for i, year in enumerate(years):
    ndvi = da.sel(year=year)
    img = ndvi.squeeze().values

    im = axes[i].imshow(
        img, cmap=ndvi_cmap, norm=norm,
        extent=[lon.min(), lon.max(), lat.min(), lat.max()],
        origin='upper'
    )

    axes[i].set_title(f"NDVI {year}", fontsize=14)
    axes[i].set_xlabel('Longitude', fontsize=12)
    axes[i].set_ylabel('Latitude', fontsize=12)

    # Format tick labels to one decimal place
    axes[i].xaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[i].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))

# Add colorbar
cbar = fig.colorbar(im, ax=axes, orientation='vertical', fraction=0.03, pad=0.02)
cbar.set_label('NDVI', fontsize=14)
cbar.set_ticks([-1, -0.5, 0, 0.25, 0.5, 0.75, 1])
cbar.ax.set_yticklabels(['<0', '-0.5', '0', '0.25', '0.5', '0.75', '1'])

plt.show()

from google.colab import drive
drive.mount('/content/drive')

# Save figure to Google Drive
plt.savefig('/content/drive/MyDrive/NDVI_maps.png', dpi=300, bbox_inches='tight')

plt.figure(figsize=(10,6))

# Your line plot code here...
# plt.plot(...)

# Save the figure
plt.savefig("Mean_NDVI_per_year.png", dpi=300, bbox_inches='tight')
plt.savefig("Mean_NDVI_per_year.pdf", dpi=300, bbox_inches='tight')

!pip install contextily geopandas

import geopandas as gpd
import contextily as ctx
import matplotlib.pyplot as plt

import matplotlib.pyplot as plt
from matplotlib.ticker import FormatStrFormatter
import matplotlib.colors as mcolors

fig, axes = plt.subplots(3, 3, figsize=(12,10), constrained_layout=True)
axes = axes.flatten()

vmin, vmax = -1, 1  # NDVI range

# Use x and y as lon/lat
lon = da.x.values
lat = da.y.values

# NDVI colormap: brown → yellow → green
ndvi_cmap = plt.get_cmap('RdYlGn')
norm = mcolors.Normalize(vmin=vmin, vmax=vmax)

for i, year in enumerate(years):
    ndvi = da.sel(year=year)
    img = ndvi.squeeze().values

    im = axes[i].imshow(
        img, cmap=ndvi_cmap, norm=norm,
        extent=[lon.min(), lon.max(), lat.min(), lat.max()],
        origin='upper'
    )

    axes[i].set_title(f"NDVI {year}", fontsize=14)
    axes[i].set_xlabel('Longitude', fontsize=12)
    axes[i].set_ylabel('Latitude', fontsize=12)

    # Format tick labels to one decimal place
    axes[i].xaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[i].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))

# Add colorbar
cbar = fig.colorbar(im, ax=axes, orientation='vertical', fraction=0.03, pad=0.02)
cbar.set_label('NDVI', fontsize=14)
cbar.set_ticks([-1, -0.5, 0, 0.25, 0.5, 0.75, 1])
cbar.ax.set_yticklabels(['<-0.7', '-0.5', '0', '0.25', '0.5', '0.75', '1'])


# Save map at high resolution
fig.savefig('/content/NDVI_maps.png', dpi=300, bbox_inches='tight')
print("NDVI maps saved to /content/NDVI_maps.png")

plt.show()

# ---- Mean NDVI per year graph ----
mean_ndvi = [da.sel(year=year).mean().values for year in years]

plt.figure(figsize=(9, 4))
plt.plot(years, mean_ndvi, marker='o', color='green', linewidth=2)
plt.title('Mean NDVI per Year', fontsize=16, fontweight='bold')
plt.xlabel('Year', fontsize=14)
plt.ylabel('Mean NDVI', fontsize=14)
plt.ylim(-0.1, 1)
plt.grid(True, linestyle='--', alpha=0.6)

# Colored markers based on NDVI value
for x_val, y_val in zip(years, mean_ndvi):
    if y_val < 0: color = 'blue'
    elif y_val < 0.2: color = 'brown'
    elif y_val < 0.5: color = 'orange'
    else: color = 'green'
    plt.scatter(x_val, y_val, color=color, s=100, edgecolor='k', zorder=5)

# Save graph at high resolution
plt.savefig('/content/Mean_NDVI_per_year.png', dpi=300, bbox_inches='tight')
print("Mean NDVI graph saved to /content/Mean_NDVI_per_year.png")

plt.show()

from google.colab import files

files.download('/content/NDVI_maps.png')
files.download('/content/Mean_NDVI_per_year.png')

import matplotlib.pyplot as plt
from matplotlib.ticker import FormatStrFormatter
import matplotlib.colors as mcolors

fig, axes = plt.subplots(3, 3, figsize=(12,10), constrained_layout=True)
axes = axes.flatten()

vmin, vmax = -1, 1  # NDVI range

# Use x and y as lon/lat
lon = da.x.values
lat = da.y.values

# NDVI colormap: brown → yellow → green
ndvi_cmap = plt.get_cmap('RdYlGn')
norm = mcolors.Normalize(vmin=vmin, vmax=vmax)

for i, year in enumerate(years):
    ndvi = da.sel(year=year)
    img = ndvi.squeeze().values

    im = axes[i].imshow(
        img, cmap=ndvi_cmap, norm=norm,
        extent=[lon.min(), lon.max(), lat.min(), lat.max()],
        origin='upper'
    )

    axes[i].set_title(f"NDVI {year}", fontsize=14)
    axes[i].set_xlabel('Longitude', fontsize=12)
    axes[i].set_ylabel('Latitude', fontsize=12)

    axes[i].xaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    axes[i].yaxis.set_major_formatter(FormatStrFormatter('%.1f'))

# Add colorbar
cbar = fig.colorbar(im, ax=axes, orientation='vertical', fraction=0.03, pad=0.02)
cbar.set_label('NDVI', fontsize=14)
cbar.set_ticks([-1, -0.5, 0, 0.25, 0.5, 0.75, 1])
cbar.ax.set_yticklabels(['<-0.7', '-0.5', '0', '0.25', '0.5', '0.75', '1'])

fig.savefig('/content/NDVI_maps.png', dpi=300, bbox_inches='tight')
print("NDVI maps saved to /content/NDVI_maps.png")

plt.show()

# ---- Mean NDVI per year graph ----
mean_ndvi = [da.sel(year=year).mean().values for year in years]

# -------- ADD THIS LINE (STD calculation) --------
std_ndvi = [da.sel(year=year).std().values for year in years]

plt.figure(figsize=(9, 4))

# -------- ADD ERROR BARS --------
plt.errorbar(years, mean_ndvi, yerr=std_ndvi, fmt='o-', color='green',
             linewidth=2, capsize=5)

plt.title('Mean NDVI per Year', fontsize=16, fontweight='bold')
plt.xlabel('Year', fontsize=14)
plt.ylabel('Mean NDVI', fontsize=14)
plt.ylim(-0.1, 1)
plt.grid(True, linestyle='--', alpha=0.6)

# Colored markers based on NDVI value
for x_val, y_val in zip(years, mean_ndvi):
    if y_val < 0: color = 'blue'
    elif y_val < 0.2: color = 'brown'
    elif y_val < 0.5: color = 'orange'
    else: color = 'green'
    plt.scatter(x_val, y_val, color=color, s=100, edgecolor='k', zorder=5)

plt.savefig('/content/Mean_NDVI_per_year.png', dpi=300, bbox_inches='tight')
print("Mean NDVI graph saved to /content/Mean_NDVI_per_year.png")

plt.show()